The format of the contact plan file is `.ccp`, which stands for _Core Contact Plan_ and is taken from the https://github.com/gh0st42/ccm/[Core Contact Manager], a fluctuating connectivity simulator for the https://github.com/coreemu/core[core network emulator]. 
This file defines the communication links between nodes, including properties such as bandwidth, delay, loss, and jitter. 
The contact plan is essential for simulating realistic network conditions in NSE2.

Links between nodes can be fixed or fluctuating, and the plan can either be configured to have symmetric (one line per node pair) or asymmetric links (two lines per node pair - one per direction).

Each dynamic contact is defined by a time window, which specifies when the contact is active.
Other tools can be used to simulate actual node movement and calculate visibility for the contact plan from this. 
The contact plan file is structured in a way that allows for easy parsing and integration with NSE2.

// === Example Contact Plan

[source, id="exampleSimpleContacts2"]
----
# each entry starts with "a contact" or "a fixed"	
# a fixed <node id 1 OR name> <node id 2 OR name OR dev:<interfacename> > <bandwidth> [loss%] [delay] [jitter]
# a contact <begin timestamp in seconds> <end timestamp in seconds> <node id 1 OR name> <node id 2 OR name OR dev:<interfacename> > <bandwidth> [loss%] [delay] [jitter]

include::../../../../scenarios/simple/contacts.ccp[]
----

Optionally, variables such as `loop` can be `s` et to 1 to indicate that the contact plan should be repeated indefinitely if the simulation runs longer than the last timestamp. This can also be overriden by the `--loop` command line option when starting the simulation with `nse2_contacts`.

The first node must always be specified by its name, while the second node can be specified by its name or by its interface name (e.g., `dev:eth0`).
This allows for flexibility in defining contacts, especially in scenarios where nodes have multiple interfaces to the same next-hop node or are part of a larger network topology.

[TIP] 
====
For convenience, the bandwidth can be specified in various units, such as `kbit`, `mbit` or `gbit`.
----
a contact 20 40 n3 n2 2mbit 0.0 0.01 0.0
----
====

IMPORTANT: When a contact plan was designed with symmetric links in mind, it is necessary to use the `--symmetric` command line option when starting the simulation with `nse2_contacts` to automatically create the second line for each contact.

TIP: You can interact with the contact plan file using `nse2_cmd` to get information about the running scenario, current links, and other properties. Additionally, you can control the playback of the contact plan, such as pausing or resuming the simulation, skipping to the next event, etc. This is useful for debugging and testing scenarios with dynamic contacts.